version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tanstack-kit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tanstack-kit
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: test
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tanstack-kit']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

